
/**
-------------------------------------------------------------------------------
This source code has been generated by class generator app.
-------------------------------------------------------------------------------
 */

/*---------------------------------------------------------------------------*/
/* Class [nombre_clase] */
/*---------------------------------------------------------------------------*/

//-------------------------------- NO TOCAR!!! --------------------------------
//Constructor obligatorio
YoreSoftware.JSGE.[nombre_clase] = function(params) {
	this.__class_extends(params);
};

//Atributos obligatorios
YoreSoftware.JSGE.[nombre_clase].prototype.__class_extends = YoreSoftware.JSGE.__class_extends;
YoreSoftware.JSGE.[nombre_clase].prototype.__classname = "[nombre_clase]";
YoreSoftware.JSGE.[nombre_clase].prototype.__super = [nombre_superclase];
//FIN ------------------------------ NO TOCAR!!! ------------------------------


//---------------------------- Atributos de la clase --------------------------
//Creación e inicialización de los atributos de la clase
[Atributos_clase]
//YoreSoftware.JSGE.[nombre_clase].prototype.[nombre_atributo1] = [valor_atributo1];
//YoreSoftware.JSGE.[nombre_clase].prototype.[nombre_atributo2] = [valor_atributo2];
//Etc, etc, etc
//FIN ------------------------- Atributos de la clase -------------------------


//-------------------------- Constructor de la clase --------------------------
/* Método que se usa como constructor de la clase.
 * En este método "__self" hace la función de "this" y el parámetro
 * de entrada "params" contiene los parámetros en forma de Objeto:
 * {
 * 		param1 : valor_param1,
 * 		param2 : valor_param2,
 * 		etc...
 * }
 */
YoreSoftware.JSGE.Animal.prototype.__init = function(__self, params) {
	/* Modo de asignar los valores de "params" en los atributos de
	 * la clase:
	 * __self.atributo1 = params.nombre_param1;
	 * __self.atributo2 = params.nombre_param2;
	 */
	
};
//FIN------------------------ Constructor de la clase -------------------------


//---------------------------- Métodos de la clase ----------------------------
//Métodos de la clase
YoreSoftware.JSGE.[nombre_clase].prototype.[nombre_método1] = function() {
	
};

YoreSoftware.JSGE.[nombre_clase].prototype.[nombre_método2] = function() {
	
};
//FIN-------------------------- Métodos de la clase ---------------------------
